//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_REST.DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class db_PruebaEntities : DbContext
    {
        public db_PruebaEntities()
            : base("name=db_PruebaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual ObjectResult<SP_GET_USER_Result> SP_GET_USER(Nullable<decimal> iD_USUARIO)
        {
            var iD_USUARIOParameter = iD_USUARIO.HasValue ?
                new ObjectParameter("ID_USUARIO", iD_USUARIO) :
                new ObjectParameter("ID_USUARIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GET_USER_Result>("SP_GET_USER", iD_USUARIOParameter);
        }
    
        public virtual int SP_INSERT_USER(string nOMBRE, string rOL, string cONTRASENA, string eMAIL, string rUT)
        {
            var nOMBREParameter = nOMBRE != null ?
                new ObjectParameter("NOMBRE", nOMBRE) :
                new ObjectParameter("NOMBRE", typeof(string));
    
            var rOLParameter = rOL != null ?
                new ObjectParameter("ROL", rOL) :
                new ObjectParameter("ROL", typeof(string));
    
            var cONTRASENAParameter = cONTRASENA != null ?
                new ObjectParameter("CONTRASENA", cONTRASENA) :
                new ObjectParameter("CONTRASENA", typeof(string));
    
            var eMAILParameter = eMAIL != null ?
                new ObjectParameter("EMAIL", eMAIL) :
                new ObjectParameter("EMAIL", typeof(string));
    
            var rUTParameter = rUT != null ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERT_USER", nOMBREParameter, rOLParameter, cONTRASENAParameter, eMAILParameter, rUTParameter);
        }
    
        public virtual ObjectResult<SP_LOGIN_USER_Result> SP_LOGIN_USER(string rUT, string pASS)
        {
            var rUTParameter = rUT != null ?
                new ObjectParameter("RUT", rUT) :
                new ObjectParameter("RUT", typeof(string));
    
            var pASSParameter = pASS != null ?
                new ObjectParameter("PASS", pASS) :
                new ObjectParameter("PASS", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LOGIN_USER_Result>("SP_LOGIN_USER", rUTParameter, pASSParameter);
        }
    }
}
